"""empty message

Revision ID: 6a592074670d
Revises: 
Create Date: 2021-09-13 17:46:22.402619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a592074670d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=24), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'student', 'stream', ['stream_id'], ['id'])
    op.create_foreign_key(None, 'student', 'college', ['college_id'], ['id'])
    op.drop_column('student', 'college')
    op.drop_column('student', 'stream')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('stream', sa.VARCHAR(length=255), nullable=True))
    op.add_column('student', sa.Column('college', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_table('course')
    # ### end Alembic commands ###
